name: GitLab Sync

on: [ push ]

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:FloBoJa/Battleship-Plus.git"
          source_branch: ${{ github.head_ref }}
          destination_repo: "git@git.scc.kit.edu:tm-praktika/protocol-engineering-ws2022-2023/groups/implementation-group-a.git"
          destination_branch: ${{ github.head_ref }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
