name: GitLab Sync

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:FloBoJa/Battleship-Plus.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@git.scc.kit.edu:tm-praktika/protocol-engineering-ws2022-2023/groups/implementation-group-a.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
